# Generated by Django 3.1 on 2020-09-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ['-last_message__timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='text of message')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='message creation timestamp')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='username from django user model (no need in sql query for getting related django`s user model)')),
                ('avatar_url', models.URLField(blank=True, default='https://www.clarity-enhanced.net/wp-content/uploads/2020/06/filip.jpg', verbose_name='url of the profile`s avatar')),
                ('profile_description', models.CharField(blank=True, max_length=64, verbose_name='text description (status) of profile written by user')),
                ('friend_list', models.ManyToManyField(blank=True, related_name='_profile_friend_list_+', to='chat.Profile', verbose_name='list of friend`s profiles')),
            ],
        ),
    ]
