# Generated by Django 3.1 on 2020-09-27 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200925_1342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['last_message__timestamp']},
        ),
    ]
