# Generated by Django 3.1 on 2020-08-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chat_last_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='title',
        ),
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.AddField(
            model_name='chat',
            name='message_list',
            field=models.ManyToManyField(blank=True, related_name='chat', to='chat.Message'),
        ),
    ]
