# Generated by Django 3.1 on 2020-08-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_auto_20200822_0754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='message_list',
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='message_list', to='chat.chat'),
            preserve_default=False,
        ),
    ]
