# Generated by Django 3.1 on 2020-09-24 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_auto_20200822_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-last_message__timestamp']},
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, verbose_name='url of the profile`s avatar'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_message_in_chat', to='chat.message', verbose_name='the last message written in this chat'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='participant_list',
            field=models.ManyToManyField(blank=True, related_name='chat_list', to='chat.Profile', verbose_name='list of chat participant`s profiles'),
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_list', to='chat.profile', verbose_name='profile model of the message`s author'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_list', to='chat.chat', verbose_name='chat`s model in which message was created'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='text of message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='message creation timestamp'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friend_list',
            field=models.ManyToManyField(blank=True, related_name='_profile_friend_list_+', to='chat.Profile', verbose_name='list of friend`s profiles'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_description',
            field=models.CharField(blank=True, max_length=64, verbose_name='text description (status) of profile written by user'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='django user model related to this profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=64, verbose_name='username from django user model (no need in sql query for getting related django`s user model)'),
        ),
    ]
