# Generated by Django 3.1 on 2020-09-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20200924_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, default='https://www.clarity-enhanced.net/wp-content/uploads/2020/06/filip.jpg', verbose_name='url of the profile`s avatar'),
        ),
    ]
