export const AUTH_START = "AUTH_START/AUTH";
export const AUTH_SUCCESS = "AUTH_SUCCESS/AUTH";
export const AUTH_FAIL = "AUTH_FAIL/AUTH";
export const AUTH_LOGOUT = "AUTH_LOGOUT/AUTH";

export const NEW_MESSAGE = "NEW_MESSAGE/CHAT";
export const NEW_CHAT = "NEW_CHAT/CHAT";
export const SET_MESSAGE_LIST_AND_COMPANION_PROFILE =
  "SET_MESSAGE_LIST_AND_COMPANION_PROFILE/CHAT";
export const SET_MESSAGE_LIST_CHUNK = "SET_MESSAGE_LIST_CHUNK/CHAT";
export const GET_CHAT_LIST_AND_INFO_SUCCESS =
  "GET_CHAT_LIST_AND_INFO_SUCCESS/CHAT";
export const CHANGE_CHAT_ID = "CHANGE_CHAT_ID/CHAT";
export const CHANGE_ACTIVE_CHAT_ID = "CHANGE_ACTIVE_CHAT_ID/CHAT";

export const GET_FRIEND_LIST_SUCCESS = "GET_FRIEND_LIST_SUCCESS/PROFILE";
